//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cantalaloun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        public int groupID { get; set; }
        public string groupName { get; set; }
        public Nullable<int> memberID { get; set; }
        public Nullable<int> songID { get; set; }
    }
}
