//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cantalaloun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Members
    {
        public int memberID { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public Nullable<int> telephone { get; set; }
        public string mail { get; set; }
        public string ektasi { get; set; }
        public Nullable<int> songID { get; set; }
        public Nullable<int> groupID { get; set; }
    }
}
