//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cantalaloun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rehearsal
    {
        public int rehearsalId { get; set; }
        public string date { get; set; }
        public string songID { get; set; }
        public string memberID { get; set; }
    }
}
